# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

#name: $(Version.MajorMinor).$(Version.Revision)-$(Date:yyyyMMdd)-$[coalesce()]$(Build.SourceBranchName)
name: $(Date:yyyyMMdd)$(Rev:.r)-$(Build.SourceBranchName)

trigger:
- master
- dev

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  #Version.MajorMinor: 0.1
  #Version.Revision: $[counter(variables['Version.MajorMinor'], 0)]

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*Test/*.csproj'
    arguments: '--no-build --configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Include="[OPCAIC*]*"'
- script: |
    dotnet tool install -g dotnet-reportgenerator-globaltool
    reportgenerator -reports:$(Build.SourcesDirectory)/test/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/CodeCoverage -reporttypes:"HtmlInline_AzurePipelines;Cobertura"
  displayName: Generate code coverage report
  condition: succeededOrFailed()
- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage report'
  condition: succeededOrFailed()
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.SourcesDirectory)/CodeCoverage/Cobertura.xml'
    reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage'
- task: DotNetCoreCLI@2
  displayName: 'Publish ApiService'
  condition: and(succeeded(), not(eq(variables['Build.Reason'], 'PullRequest')))
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
- task: DotNetCoreCLI@2
  displayName: 'Publish worker'
  condition: and(succeeded(), not(eq(variables['Build.Reason'], 'PullRequest')))
  inputs:
    command: publish
    publishWebProjects: False
    projects: '**/*.Worker.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts.'
  condition: and(succeeded(), not(eq(variables['Build.Reason'], 'PullRequest')))